version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  build-and-test:
    executor: docker/docker
    steps:
      - checkout
      - run:
          command: ./batect setup
          name: Setup dependencies
      - run:
          command: ./batect unit_test
          name: Run unit tests
  train-model:
    steps:
      - checkout
      - run:
          command: ./batect train_model
          name: Train ML model

workflows:
  main:
    jobs:
      - build-and-test
      - train-model
