# docs: https://batect.dev/tools/CircleCI.html
version: 2.1

jobs:
  build-and-test:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          command: ./batect setup
          name: Setup dependencies
      - run:
          command: ./batect unit_test
          name: Run unit tests
  train-model:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          command: ./batect train_model
          name: Train ML model

workflows:
  main:
    jobs:
      - build-and-test
      - train-model:
          requires:
            - build-and-test
