# docs: https://batect.dev/tools/CircleCI.html
version: 2.1

jobs:
  build-and-test:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    environment:
      BATECT_CACHE_TYPE: directory
    steps:
      - batect:
          task: setup
      - batect:
          task: unit_test
  train-model:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    environment:
      BATECT_CACHE_TYPE: directory
    steps:
      - batect:
          task: train_model

workflows:
  main:
    jobs:
      - build-and-test
      - train-model:
          requires:
            - build-and-test

commands:
  batect:
    description: "Run a task using batect"
    parameters:
      task:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: batect-caches-{{ arch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          command: ./batect << parameters.task >>
      - save_cache:
          key: batect-caches-{{ arch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - .batect/caches
